### ISSUE TITLE
Improved japanese translation

### ISSUE THREAD

**Issue by Catastravia** [insin/control-panel-for-youtube#22]
I'm sorry if this is the wrong place. (I'm newbie)

My suggestion includes two modifications.
• Correcting the spelling discrepancies, e.g., オートプレイ to 自動再生.
• Correcting unnatural expressions to natural, e.g., ギャップ to 隙間.

[messages.json](https://github.com/insin/control-panel-for-youtube/files/14414958/messages.json)

**Comment by insin** [comment]
This is the right place, thank you very much, I'll look at getting these fixes into the next version.
