### ISSUE TITLE
Request to support Firefox ESR

### ISSUE THREAD

**Issue by nateify** [insin/control-panel-for-youtube#30]
The current minimum version in the manifest 121 leaves current Firefox ESR 115 unable to install the extension. This version of Firefox will still be supported until October 2024 until it is superseded by 128. If technically feasible I would like for this extension to allow current ESR version support.

**Comment by insin** [comment]
There are currently 49 CSS `:has()` selectors used to hide things at the appropriate level to avoid leaving gaps in the layout, without having to manually traverse the DOM, so I'm not sure many features would be left standing if we removed the current minimum version requirement.

**Comment by nateify** [comment]
Is this the only limitation? If so I might try side-loading the extension as I already have `layout.css.has-selector.enabled` enabled.

**Comment by insin** [comment]
Yes, that's the only reason the minimum version is set.

The main content script is also usable as a user script:

https://github.com/insin/control-panel-for-youtube/blob/main/content.js

Greasy Fork is always the first place to have the latest release available:

https://greasyfork.org/en/scripts/488224-control-panel-for-youtube

**Comment by nateify** [comment]
Thanks, I am able to use it that way and it works with layout.css.has-selector.enabled

**Comment by realAzazello** [comment]
@nateify (or anyone): I'm also on ESR 115 and interested in trying this app. Set <layout.css.has-selector.enabled> to true. Obviously cannot install from AMO. Installed the userscript from GF, but there's no icon to get to the control panel. The script definitely does not use GM_registerMenuCommand, so no luck on having TM menus.

How can the script be configured without a menu or panel?

Firefox ESR 115
Tampermonkey v5.1.1

**Comment by nateify** [comment]
> @nateify (or anyone): I'm also on ESR 115 and interested in trying this app. Set <layout.css.has-selector.enabled> to true. Obviously cannot install from AMO. Installed the userscript from GF, but there's no icon to get to the control panel. The script definitely does not use GM_registerMenuCommand, so no luck on having TM menus.
> 
> How can the script be configured without menus or panels?
> 
> Firefox ESR 115 Tampermonkey v5.1.1

ESR 128.3 has already been released to 115 users, unless you are on Windows 7 or 8.1.

However you can use the extension directly from GitHub if you alter the manifest to allow 115 as a minimum version, which is what I did. You will get a warning but the extension will install. Then the options menu is usable in Firefox natively
