### ISSUE TITLE
"Hide watched videos" should be off by default

### ISSUE THREAD

**Issue by willwillems** [insin/control-panel-for-youtube#56]
Love this plugin, but this option leads to super trippy behavior. Watch a video and search for it later? It's as if it never existed, literally unfindable.

Perhaps this option should just be completely disabled in the search results. I don't know how it would be desirable to be literally unable to find a song on YouTube after you have listened to it once.

**Comment by realAzazello** [comment]
Agreed.

For this feature I use another script-- EvHaus' [Youtube: Hide Watched Videos](https://github.com/EvHaus/youtube-hide-watched) which has buttons to quickly on/off the option.

**Comment by insin** [comment]
Yup, this should be disabled in Search results.
